import Head from "next/head";
import Board from "@/components/Board";
import Matrix from "@/dataStructures/matrix";
import Link from "next/link";
export default function Home() {
  return (
    <>
      <Head>
        <title>chess</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Link rel="icon" href="/favicon.ico" />
      </Head>
      <Board matrix={new Matrix()} />
    </>
  );
}
